[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["MyWork Digital Startup <cliente@mywork.digital>"]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.3",
    "opencv-python>=4.11.0.86",
    "streamlit>=1.50.0",
]
